<?php
//////////////////////////////////////////////////////////////////////
// Created by zerilliworks
// Date: 4/30/14
// Time: 5:41 PM
// For: CookieSync


namespace CookieSync\Cache;


use Illuminate\Support\ServiceProvider;

class CacheServiceProvider extends ServiceProvider {

    protected $defer = false;

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind('cookiesync.cache.namespacer', 'CookieSync\Cache\CacheNamespacer');
        $this->app->bind('cookiesync.listcache', 'CookieSync\Cache\ListCache');
        $this->app->bind('cookiesync.object_cache', 'CookieSync\Cache\ObjectCache');
    }

    public function provides()
    {
        return ['cookiesync.listcache'];
    }


}
